Repository binbat/live777, pull requests merged in 2024-12, with the labels that each got.

#259 refactor(docs): refine vitepress config
  docs/.vitepress/config/en.ts
  docs/.vitepress/config/index.ts
  docs/.vitepress/config/shared.ts
  docs/.vitepress/config/types.d.ts
  docs/.vitepress/config/zh.ts
Labels: documentation

#260 feat(web): update ui after login or stream operation
  web/liveion/components/login.tsx
  web/liveman/components/nodes-table.tsx
  web/liveman/liveman.tsx
  web/shared/api.ts
  web/shared/authorization-middleware.ts
  web/shared/components/dialog-clients.tsx
  web/shared/components/dialog-new-stream.tsx
  web/shared/components/page-layout.tsx
  web/shared/components/streams-table.tsx
Labels: bug

#258 Feat/liveman url query parameter
  liveman/src/route/proxy.rs
  liveman/src/route/stream.rs
Labels: enhancement, mod::liveman

#261 refactor: return &'static str when returning String is unnecessary
  .github/CLA.md
  libs/api/src/path.rs
  libs/signal/src/lib.rs
  liveion/src/route/strategy.rs
  liveion/src/route/stream.rs
Labels: mod::live777

#262 refactor: use format_args!() when String creation is unnecessary
  livetwo/src/rtspclient.rs
Labels: mod::live777

#263 feat(web): liveman sub-dashboard for specific nodes
  docs/.vitepress/config/index.ts
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  web/liveion/components/login.tsx
  web/liveman/api.ts
  web/liveman/components/login.tsx
  web/liveman/components/nodes-table.tsx
  web/liveman/liveman.tsx
  web/shared/components/dialog-preview.tsx
  web/shared/components/dialog-web-stream.tsx
  web/shared/components/streams-table.tsx
  web/shared/hooks/use-refresh-timer.ts
  web/shared/tools/debugger/compat.tsx
  web/tailwind.config.ts
  web/vite.config.ts
Labels: enhancement, mod::webui, mod::liveman

#264 feat(web): persist token to localStorage
  web/liveman/components/login.tsx
  web/liveman/components/nodes-table.tsx
  web/liveman/liveman.tsx
  web/shared/components/streams-table.tsx
  web/shared/hooks/use-refresh-timer.ts
Labels: mod::webui, mod::liveman
