Repository binbat/live777, pull requests merged in 2024-07, with the labels that each got.

#189 feat(web): split liveion and liveman dashboard
  README.md
  bun.lockb
  index.html
  liveion/src/lib.rs
  liveman/src/main.rs
  package-lock.json
  package.json
  tsconfig.node.json
  vite.config.ts
  web/app.css
  web/liveion/index.html
  web/liveion/liveion.tsx
  web/liveion/main.tsx
  web/liveion/tools/debugger.html
  web/liveion/tools/debugger.ts
  web/liveion/tools/player.html
  web/liveion/tools/player.ts
  web/liveion/vite.config.ts
  web/liveman/api.ts
  web/liveman/index.html
  web/liveman/liveman.tsx
  web/liveman/main.tsx
  web/liveman/nodes-table.tsx
  web/liveman/tools/debugger.html
  web/liveman/tools/debugger.ts
  web/liveman/tools/player.html
  web/liveman/tools/player.ts
  web/liveman/vite.config.ts
  web/main.tsx
  web/public/logo.svg
  web/shared/api.ts
  web/shared/components/dialog-cascade.tsx
  web/shared/components/dialog-clients.tsx
  web/shared/components/dialog-new-stream.tsx
  web/shared/components/dialog-preview.tsx
  web/shared/components/dialog-web-stream.tsx
  web/shared/components/live777-logo.tsx
  web/shared/components/streams-table.tsx
  web/shared/components/styled-checkbox.tsx
  web/shared/hooks/use-logger.ts
  web/shared/hooks/use-refresh-timer.ts
  web/shared/index.css
  web/shared/tools/debugger.html
  web/shared/tools/debugger/compat.tsx
  web/shared/tools/debugger/components/data-channel.js
  web/shared/tools/debugger/components/debug-player.js
  web/shared/tools/debugger/components/video-size-select.js
  web/shared/tools/debugger/debugger.css
  web/shared/tools/debugger/debugger.js
  web/shared/tools/debugger/main.tsx
  web/shared/tools/debugger/sdp.js
  web/shared/tools/player/main.tsx
  web/shared/tools/player/player.tsx
  web/shared/tools/player/style.css
  web/shared/utils.ts
  web/uno.config.ts
  web/vite.config.ts
Labels: enhancement, mod::webui

#192 feat(web): log inbound-rtp bytesReceived before video canplay
  web/shared/components/dialog-new-stream.tsx
  web/shared/components/dialog-preview.tsx
Labels: bug, enhancement, mod::webui

#195 feat(web): make log timestamp more human readable
  web/shared/components/dialog-web-stream.tsx
  web/shared/hooks/use-logger.ts
Labels: enhancement, mod::webui

#194 feat(liveion): disabled mDNS send
  liveion/src/forward/internal.rs
Labels: bug, enhancement

#196 Fix live777 on_track will not be fired. mid RTP Extensions required for Simulcast
  liveion/src/forward/internal.rs
  liveion/src/forward/mod.rs
  liveion/src/forward/publish.rs
  liveion/src/forward/subscribe.rs
  liveion/src/forward/track.rs
  liveion/src/lib.rs
  liveion/src/macro.rs
  liveion/src/stream/manager.rs
Labels: bug, mod::live777

#197 feat(infra): update dockerfile
  .github/workflows/docker-client.yml
  .github/workflows/docker.yml
  docker/Dockerfile.gstreamer
  docker/Dockerfile.live777
  docker/Dockerfile.liveman
Labels: mod::infra

#193 update(deps): webrtc version
  Cargo.lock
  Cargo.toml
  conf/live777.toml
  libs/libwish/src/lib.rs
  liveion/src/config.rs
  tools/whepfrom/src/main.rs
  tools/whipinto/src/main.rs
  tools/whipinto/src/test.rs
Labels: mod::live777

#200 feat(web): stream table manual refresh and cascade dialog improvements
  web/shared/components/dialog-cascade.tsx
  web/shared/components/streams-table.tsx
  web/shared/components/styled-checkbox.tsx
  web/shared/hooks/use-refresh-timer.ts
  web/shared/utils.ts
Labels: enhancement, mod::webui

#201 Break change cascade api
  libs/api/src/request.rs
  libs/api/src/response.rs
  libs/libwish/src/lib.rs
  liveion/src/convert.rs
  liveion/src/forward/internal.rs
  liveion/src/forward/message.rs
  liveion/src/forward/mod.rs
  liveion/src/forward/publish.rs
  liveion/src/forward/subscribe.rs
  liveion/src/route/admin.rs
  liveion/src/stream/manager.rs
  liveman/src/route/utils.rs
  liveman/src/tick.rs
  web/shared/api.ts
  web/shared/components/dialog-cascade.tsx
Labels: mod::live777

#202 Feat liveman disable cascade button
  README.md
  web/liveion/liveion.tsx
  web/liveman/liveman.tsx
  web/shared/components/streams-table.tsx
Labels: enhancement, mod::webui

#185 Docs
  .gitignore
  README.md
  docs/.vitepress/config/en.ts
  docs/.vitepress/config/index.ts
  docs/.vitepress/config/shared.ts
  docs/.vitepress/config/zh.ts
  docs/guide/developer.md
  docs/guide/ffmpeg.md
  docs/guide/getting-started.md
  docs/guide/gstreamer.md
  docs/guide/install.md
  docs/guide/introduction.md
  docs/guide/live777-api.md
  docs/guide/liveman-api.md
  docs/guide/obs-studio.md
  docs/guide/vlc.md
  docs/guide/what-is-live777.md
  docs/index.md
  docs/live777-cascade.excalidraw.svg
  docs/public/live777-apps.excalidraw.svg
  docs/public/live777-arch.excalidraw.svg
  docs/public/live777-cluster.excalidraw.svg
  docs/public/logo.svg
  docs/public/obs-whip.avif
  docs/public/webrtc-mesh-mcu-sfu.excalidraw.svg
  docs/zh/guide/developer.md
  docs/zh/guide/ffmpeg.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/gstreamer.md
  docs/zh/guide/install.md
  docs/zh/guide/introduction.md
  docs/zh/guide/live777-api.md
  docs/zh/guide/liveman-api.md
  docs/zh/guide/obs-studio.md
  docs/zh/guide/vlc.md
  docs/zh/guide/what-is-live777.md
  docs/zh/index.md
  package-lock.json
  package.json
Labels: documentation

#207 refactor: migrate e2e:cluster to vitest
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/wish.yml
  cluster.test.ts
  eslint.config.js
  package-lock.json
  package.json
Labels: mod::infra

#211 Refactor RTSP session handling
  tools/whipinto/src/rtspclient.rs
Labels: enhancement, mod::whipinto

#209 Feat whipinto rtsp
  Cargo.lock
  docs/guide/ffmpeg.md
  docs/zh/guide/ffmpeg.md
  libs/rtsp/Cargo.toml
  libs/rtsp/src/lib.rs
  tools/whepfrom/Cargo.toml
  tools/whepfrom/src/main.rs
  tools/whipinto/Cargo.toml
  tools/whipinto/src/main.rs
  tools/whipinto/src/payload.rs
  tools/whipinto/src/rtspclient.rs
Labels: enhancement, mod::whipinto
