Repository binbat/live777, pull requests merged in 2024-11, with the labels that each got.

#240 WebUI new design
  eslint.config.js
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  web/liveion/components/login.tsx
  web/liveion/liveion.tsx
  web/liveion/main.tsx
  web/liveman/api.ts
  web/liveman/components/dialog-token.tsx
  web/liveman/components/login.tsx
  web/liveman/components/nodes-table.tsx
  web/liveman/liveman.tsx
  web/liveman/main.tsx
  web/shared/api.ts
  web/shared/authorization-middleware.ts
  web/shared/components/dialog-cascade.tsx
  web/shared/components/dialog-clients.tsx
  web/shared/components/dialog-new-stream.tsx
  web/shared/components/dialog-preview.tsx
  web/shared/components/dialog-web-stream.tsx
  web/shared/components/live777-logo.tsx
  web/shared/components/page-header.tsx
  web/shared/components/page-layout.tsx
  web/shared/components/streams-table.tsx
  web/shared/components/styled-checkbox.tsx
  web/shared/hooks/use-need-authorization.ts
  web/shared/index.css
  web/shared/tailwind.css
  web/shared/tools/debugger/compat.tsx
  web/shared/tools/debugger/debugger.js
  web/shared/tools/player/main.tsx
  web/shared/utils.ts
  web/tailwind.config.ts
  web/uno.config.ts
  web/vite.config.ts
Labels: enhancement, mod::webui

#248 fix(test): add test await timeout
  libs/net4mqtt/src/tests.rs
Labels: bug

#247 fix:whipinto and whepfrom mode sdp file path failed at windows
  libs/cli/src/lib.rs
  livetwo/src/whep.rs
  livetwo/src/whip.rs
  tests/tests.rs
Labels: bug, mod::whipinto, mod::whepfrom

#249 use nfpm build package deb
  .github/workflows/release.yml
  Cargo.toml
  nfpm/live777.yaml
  nfpm/liveman.yaml
  nfpm/net4mqtt.yaml
  nfpm/whepfrom.yaml
  nfpm/whipinto.yaml
Labels: enhancement, mod::infra

#250 fix coverage
  .github/workflows/grcov.yml
Labels: bug, mod::infra

#255 Feat/net4mqtt reconnect
  conf/live777.toml
  conf/liveman.toml
  libs/net4mqtt/src/proxy.rs
  liveion/src/config.rs
  liveion/src/lib.rs
  liveman/src/config.rs
  liveman/src/lib.rs
Labels: bug, enhancement, mod::live777, mod::liveman
