Repository binbat/live777, pull requests merged in 2025-04, with the labels that each got.

#274 fix stream id
  liveman/src/error.rs
  liveman/src/route/stream.rs
  web/shared/api.ts
  web/shared/components/dialog-new-stream.tsx
Labels: bug, mod::live777, mod::webui

#276 fix(web): fix liveman token restore from localStorage
  web/liveman/liveman.tsx
Labels: bug, mod::webui

#278 fix the frameRate
  web/shared/utils.ts
Labels: bug, mod::webui

#282 Refactor: remove unused 'host' parameter from Args
  livetwo/src/whep.rs
  livetwo/src/whip.rs
  src/whepfrom.rs
  src/whipinto.rs
  tests/tests.rs
Labels: mod::whipinto, mod::whepfrom

#287 fix chinese document is not translated
  .github/CLA.md
  docs/zh/guide/developer.md
  docs/zh/guide/ffmpeg.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/gstreamer.md
  docs/zh/guide/live777-api.md
  docs/zh/guide/live777.md
  docs/zh/guide/liveman-api.md
  docs/zh/guide/liveman.md
  docs/zh/guide/net4mqtt.md
  docs/zh/guide/vlc.md
  docs/zh/guide/webui.md
  docs/zh/guide/what-is-live777.md
  docs/zh/guide/whipinto.md
Labels: documentation

#292 Add Release RISC-V binary support
  .github/workflows/release.yml
Labels: enhancement, mod::infra
